build:
  image: teaci/msys$$arch
  pull: true
  shell: mingw$$arch
  commands:
    - git clean -fdx
    - mkdir -p m4
    - autoreconf -ifv
    - CFLAGS='-O3 -g' ./configure
    - make -j$(nproc)
    - make distcheck -j$(nproc)
    - cp -p libmcfgthread.dll.a  libmcfgthread-new.dll.a
    - gcc test/test.c -lmcfgthread-new -L.
# FIXME: At the moment this crashes on Wine. We must have a REAL Windows to test it.
#    - ./a

notify:
  irc:
    prefix:
    nick: mcfgthread-cibot
    channel: mcfproj
    server:
      host: chat.freenode.net
      port: 6697
      tls: true

matrix:
  arch:
    - 64
    - 32
